#!/usr/bin/env python
#-*- coding: iso-8859-1-*-

'''
sites usados na aula
Banco
http://pythonclub.com.br/gerenciando-banco-dados-sqlite3-python-parte1.html


'''

import sqlite3
conn = sqlite3.connect('auxiliar.db')
cursor = conn.cursor()

cursor.execute("""
INSERT INTO cid_sub_categoria(id,descricao) VALUES
('S655','Traumatismo de vaso(s) sangüíneo(s) de outro dedo'),
('S657','Traumatismo de vasos sangüíneos múltiplos ao nível de punho e da mão'),
('S658','Traumatismo de outros vasos sangüíneos ao nível do punho e de mão'),
('S659','Traumatismo de vaso sangüíneo não especificado ao nível do punho e da mão'),
('S660','Traumatismo do músculo flexor longo e tendão do polegar ao nível do punho e da mão'),
('S661','Traumatismo do músculo flexor e tendão de outro dedo ao nível do punho e da mão'),
('S662','Traumatismo do músculo extensor e tendão do polegar ao nível do punho e da mão'),
('S663','Traumatismo do músculo extensor e tendão de outro dedo ao nível do punho e da mão'),
('S664','Traumatismo do músculo intrínseco e tendão do polegar ao nível do punho e da mão'),
('S665','Traumatismo do músculo intrínseco e tendão de outro dedo ao nível do punho e da mão'),
('S666','Traumatismo de músculos flexores e tendões múltiplos ao nível do punho e da mão'),
('S667','Traumatismo de músculos extensores e tendões múltiplos ao nível do punho e da mão'),
('S668','Traumatismo de outros músculos e tendões ao nível do punho e da mão'),
('S669','Traumatismo de músculo e tendão não especificado ao nível do punho e da mão'),
('S670','Lesão por esmagamento do polegar e de outro(s) dedo(s)'),
('S678','Lesão por esmagamento de outras partes e das não especificadas do punho e da mão'),
('S680','Amputação traumática do polegar (completa) (parcial)'),
('S681','Amputação traumática de um outro dedo apenas (completa) (parcial)'),
('S682','Amputação traumática de dois ou mais dedos somente (completa) (parcial)'),
('S683','Amputação traumática combinada de (partes de) dedo(s) associada a outras partes do punho e da mão'),
('S684','Amputação traumática da mão ao nível do punho'),
('S688','Amputação traumática de outras partes do punho e da mão'),
('S689','Amputação traumática do punho e da mão'),
('S697','Traumatismos múltiplos do punho e da mão'),
('S698','Outros traumatismos especificados do punho e da mão'),
('S699','Traumatismo não especificados do punho e da mão'),
('S700','Contusão do quadril'),
('S701','Contusão da coxa'),
('S707','Traumatismos superficiais múltiplos do quadril e da coxa'),
('S708','Outros traumatismos superficiais do quadril e da coxa'),
('S709','Traumatismo superficial não especificado do quadril e da coxa'),
('S710','Ferimento do quadril'),
('S711','Ferimento da coxa'),
('S717','Ferimentos múltiplos do quadril e da coxa'),
('S718','Ferimentos de outras partes e das não especificadas da cintura pélvica'),
('S720','Fratura do colo do fêmur'),
('S721','Fratura pertrocantérica'),
('S722','Fratura subtrocantérica'),
('S723','Fratura da diáfise do fêmur'),
('S724','Fratura da extremidade distal do fêmur'),
('S727','Fraturas múltiplas do fêmur'),
('S728','Fraturas de outras partes do fêmur'),
('S729','Fratura do fêmur'),
('S730','Luxação da articulação do quadril'),
('S731','Entorse e distensão do quadril'),
('S740','Traumatismo do nervo ciático ao nível do quadril e da coxa'),
('S741','Traumatismo do nervo femural ao nível do quadril e da coxa'),
('S742','Traumatismo do nervo sensitivo cutâneo ao nível do quadril e da coxa'),
('S747','Traumatismo de nervos múltiplos ao nível do quadril e da coxa'),
('S748','Traumatismo de outros nervos ao nível do quadril e da coxa'),
('S749','Traumatismo de nervo não especificado ao nível do quadril e da coxa'),
('S750','Traumatismo da artéria femural'),
('S751','Traumatismo da veia femural ao nível do quadril e da coxa'),
('S752','Traumatismo da veia grande safena ao nível do quadril e da coxa'),
('S757','Traumatismo de múltiplos vasos sangüíneos ao nível do quadril e da coxa'),
('S758','Traumatismo de outros vaso sangüíneos ao nível do quadril e da coxa'),
('S759','Traumatismo de vaso sangüíneo não especificado ao nível do quadril e da coxa'),
('S760','Traumatismo do músculo e do tendão do quadril'),
('S761','Traumatismo do músculo e do tendão do quadríceps'),
('S762','Traumatismo do músculo e do tendão do adutor da coxa'),
('S763','Traumatismo do músculo e do tendão dos músculos posteriores ao nível da coxa'),
('S764','Traumatismo de outros músculos e tendões e os não especificados ao nível da coxa'),
('S767','Traumatismo de múltiplos músculos e tendões ao nível do quadril e da coxa'),
('S770','Lesão por esmagamento do quadril'),
('S771','Lesão por esmagamento da coxa'),
('S772','Lesão por esmagamento do quadril e da coxa'),
('S780','Amputação traumática na articulação do quadril'),
('S781','Amputação traumática localizada entre o joelho e o quadril'),
('S789','Amputação traumática do quadril e coxa nível não especificado'),
('S797','Traumatismos múltiplos do quadril e da coxa'),
('S798','Outros traumatismos especificados do quadril e da coxa'),
('S799','Traumatismo não especificado do quadril e da coxa'),
('S800','Contusão do joelho'),
('S801','Contusão de outras partes e de partes não especificadas da perna'),
('S807','Traumatismos superficiais múltiplos da perna'),
('S808','Outros traumatismos superficiais da perna'),
('S809','Traumatismo superficial não especificado da perna'),
('S810','Ferimento do joelho'),
('S817','Ferimentos múltiplos da perna'),
('S818','Ferimento de outras partes da perna'),
('S819','Ferimento da perna'),
('S820','Fratura da rótula [patela]'),
('S821','Fratura da extremidade proximal da tíbia'),
('S822','Fratura da diáfise da tíbia'),
('S823','Fratura da extremidade distal da tíbia'),
('S824','Fratura do perônio [fíbula]'),
('S825','Fratura do maléolo medial'),
('S826','Fratura do maléolo lateral'),
('S827','Fraturas múltiplas da perna'),
('S828','Fratura de outras partes da perna'),
('S829','Fratura da perna'),
('S830','Luxação da rótula [patela]'),
('S831','Luxação do joelho'),
('S832','Ruptura do menisco'),
('S833','Ruptura atual da cartilagem da articulação do joelho'),
('S834','Entorse e distensão envolvendo ligamento colateral (peronial) (tibial) do joelho'),
('S835','Entorse e distensão envolvendo ligamento cruzado (anterior) (posterior) do joelho'),
('S836','Entorse e distensão de outras partes e das não especificadas do joelho'),
('S837','Traumatismo de estruturas múltiplas do joelho'),
('S840','Traumatismo do nervo tibial ao nível da perna'),
('S841','Traumatismo do nervo peronial ao nível da perna'),
('S842','Traumatismo do nervo cutâneo sensitivo ao nível da perna'),
('S847','Traumatismo de múltiplos nervos ao nível da perna'),
('S848','Traumatismo de outros nervos ao nível da perna'),
('S849','Traumatismo de nervo não especificado ao nível da perna'),
('S850','Traumatismo da artéria poplítea'),
('S851','Traumatismo da artéria tibial (anterior) (posterior)'),
('S852','Traumatismo da artéria peronial'),
('S853','Traumatismo da veia grande safena ao nível da perna'),
('S854','Traumatismo da veia safena menor ao nível da perna'),
('S855','Traumatismo da veia poplítea'),
('S857','Traumatismo de múltiplos vasos sangüíneos ao nível da perna'),
('S858','Traumatismo de outros vasos sangüíneos ao nível da perna'),
('S859','Traumatismo de vasos sangüíneos não especificados ao nível da perna'),
('S860','Traumatismo do tendão de Aquiles'),
('S861','Traumatismo de outro(s) músculo(s) e tendão(ões) do grupo muscular posterior ao nível da perna'),
('S862','Traumatismo do(s) músculo(s) e tendão(ões) do grupo muscular anterior ao nível da perna'),
('S863','Traumatismo do(s) músculo(s) e tendão(ões) do grupo muscular peronial ao nível da perna'),
('S867','Traumatismo de múltiplos músculos e tendões ao nível da perna'),
('S868','Traumatismos de outros músculos e tendões ao nível da perna'),
('S869','Traumatismo de músculo e de tendão não especificado ao nível da perna'),
('S870','Traumatismo por esmagamento do joelho'),
('S878','Traumatismo por esmagamento de outra parte e de partes não especificadas da perna'),
('S880','Amputação traumática ao nível do joelho'),
('S881','Amputação traumática entre o joelho e o tornozelo'),
('S889','Amputação traumática da perna ao nível não especificado'),
('S890','Traumatismos múltiplos da perna'),
('S898','Outros traumatismos especificados da perna'),
('S899','Traumatismo não especificado da perna'),
('S900','Contusão do tornozelo'),
('S901','Contusão de artelho sem lesão da unha'),
('S902','Contusão de artelho(s) com lesão da unha'),
('S903','Contusão de outras partes e partes não especificadas do pé'),
('S907','Traumatismos superficiais múltiplos do tornozelo e do pé'),
('S908','Outros traumatismos superficiais do tornozelo e do pé'),
('S909','Traumatismo superficial do tornozelo e do pé'),
('S910','Ferimento do tornozelo'),
('S911','Ferimento do(s) artelho(s) sem lesão da unha'),
('S912','Ferimento do(s) artelho(s) com lesão da unha'),
('S913','Ferimento de outras partes do pé'),
('S917','Ferimentos múltiplos do tornozelo e do pé'),
('S920','Fratura do calcâneo'),
('S921','Fratura do astrágalo'),
('S922','Fratura de outros ossos do tarso'),
('S923','Fratura de ossos do metatarso'),
('S924','Fratura do hálux'),
('S925','Fratura de outro artelho'),
('S927','Fraturas múltiplas do pé'),
('S929','Fratura do pé não especificada'),
('S930','Luxação da articulação do tornozelo'),
('S931','Luxação do(s) artelho(s)'),
('S932','Ruptura de ligamentos ao nível do tornozelo e do pé'),
('S933','Luxação de outras partes e das não especificadas do pé'),
('S934','Entorse e distensão do tornozelo'),
('S935','Entorse e distensão do(s) artelho(s)'),
('S936','Entorse e distensão de outras partes e de partes não especificadas do pé'),
('S940','Traumatismo do nervo plantar externo (lateral)'),
('S941','Traumatismo do nervo plantar interno (medial)'),
('S942','Traumatismo nervo peronial [fibular] profundo ao nível do tornozelo e do pé'),
('S943','Traumatismo do nervo sensitivo cutâneo ao nível do tornozelo e do pé'),
('S947','Traumatismo de múltiplos nervos ao nível do tornozelo e do pé'),
('S948','Traumatismo de outros nervos ao nível do tornozelo e do pé'),
('S949','Traumatismo de nervo não especificado'),
('S950','Traumatismo da artéria dorsal do pé'),
('S951','Traumatismo da artéria plantar do pé'),
('S952','Traumatismo da veia dorsal do pé'),
('S957','Traumatismo de múltiplos vasos sangüíneos ao nível do tornozelo e do pé'),
('S958','Traumatismo de outros vasos sangüíneos ao nível do tornozelo e do pé'),
('S959','Traumatismo de vaso sangüíneo não especificado ao nível do tornozelo e do pé'),
('S960','Traumatismo do músculo e tendão do músculo flexor longo do(s) artelho(s) ao nível do tornozelo e do pé'),
('S961','Traumatismo do músculo e tendão do extensor longo do(s) artelho(s) ao nível do tornozelo e do pé'),
('S962','Traumatismo de músculo intrínseco e tendão ao nível do tornozelo e do pé'),
('S967','Traumatismo de múltiplos músculos e tendões ao nível do tornozelo e do pé'),
('S968','Traumatismo de outros tendões e músculos ao nível do tornozelo e do pé'),
('S969','Traumatismo de músculo e tendão não especificados do tornozelo e do pé'),
('S970','Lesão por esmagamento do tornozelo'),
('S971','Lesão por esmagamento do(s) artelho(s)'),
('S978','Lesão por esmagamento de outras partes do tornozelo e do pé'),
('S980','Amputação traumática do pé ao nível do tornozelo'),
('S981','Amputação traumática de apenas um artelho'),
('S982','Amputação traumática de dois ou mais artelhos'),
('S983','Amputação traumática de outras partes do pé'),
('S984','Amputação traumática do pé ao nível não especificado'),
('S997','Traumatismos múltiplos do tornozelo e do pé'),
('S998','Outros traumatismos especificados do tornozelo e do pé'),
('S999','Traumatismos não especificados do tornozelo e do pé'),
('T000','Traumatismos superficiais envolvendo a cabeça com o pescoço'),
('T001','Traumatismos superficiais envolvendo o tórax com o abdome'),
('T002','Traumatismos superficiais envolvendo regiões múltiplas do(s) membro(s) superior(es)'),
('T003','Traumatismos superficiais envolvendo regiões múltiplas do(s) membro(s) inferior(es)'),
('T006','Traumatismos superficiais envolvendo regiões múltiplas dos membros superiores com membro(s) inferiores'),
('T008','Traumatismos superficiais envolvendo outras combinações de regiões do corpo'),
('T009','Traumatismos superficiais múltiplos não especificados'),
('T010','Ferimentos envolvendo a cabeça com o pescoço'),
('T011','Ferimentos envolvendo o tórax com o abdome'),
('T012','Ferimentos envolvendo regiões múltiplas do(s) membro(s) superior(es)'),
('T013','Ferimentos envolvendo múltiplas regiões do(s) membro(s) inferior(es)'),
('T016','Ferimentos envolvendo regiões múltiplas do(s) membro(s) superior(es) com membro(s) inferior(es)'),
('T018','Ferimentos envolvendo outras combinações de regiões do corpo'),
('T019','Ferimentos múltiplos não especificados'),
('T020','Fraturas envolvendo cabeça com pescoço'),
('T021','Fraturas envolvendo tórax com parte inferior do dorso e da pelve'),
('T022','Fraturas envolvendo regiões múltiplas de um membro superior'),
('T023','Fraturas envolvendo regiões múltiplas de um membro inferior'),
('T024','Fraturas envolvendo regiões múltiplas de ambos os membros superiores'),
('T025','Fraturas envolvendo regiões múltiplas de ambos os membros inferiores'),
('T026','Fraturas envolvendo regiões múltiplas do(s) membro(s) superior(es) com inferior(es)'),
('T027','Fraturas envolvendo tórax com parte inferior do dorso e pelve com membro(s)'),
('T028','Fraturas envolvendo outras combinações de regiões do corpo'),
('T029','Fraturas múltiplas não especificadas'),
('T030','Luxações, entorses e distensões envolvendo a cabeça com o pescoço'),
('T031','Luxações, entorses e distensões envolvendo tórax com parte inferior do dorso e da pelve'),
('T032','Luxações, entorses e distensões envolvendo regiões múltiplas de membro(s) superior(es)'),
('T033','Luxações, entorses e distensões envolvendo regiões múltiplas do(s) membro(s) inferior(es)'),
('T034','Luxações, entorses e distensões envolvendo regiões múltiplas dos membros superiores com inferiores'),
('T038','Luxações, entorses e distensões envolvendo outras combinações de regiões do corpo'),
('T039','Luxações, entorses e distensões múltiplas, não especificadas'),
('T040','Traumatismos por esmagamento envolvendo a cabeça com o pescoço'),
('T041','Traumatismos por esmagamento envolvendo tórax com o abdome'),
('T042','Traumatismos por esmagamento envolvendo regiões múltiplas do(s) membro(s) superior(es)'),
('T043','Traumatismos por esmagamento envolvendo regiões múltiplas do(s) membro(s) inferior(es)'),
('T044','Traumatismos por esmagamento envolvendo regiões múltiplas do(s) membro(s) superior(es) com inferior(es)'),
('T047','Traumatismo por esmagamento do tórax com abdome'),
('T048','Traumatismos por esmagamento envolvendo outras combinações de regiões do corpo'),
('T049','Traumatismo múltiplos por esmagamento não especificados'),
('T050','Amputação traumática de ambas as mãos'),
('T051','Amputação traumática de uma mão e de um outro braço [qualquer nível'),
('T052','Amputação traumática de ambos os braços [qualquer nível]'),
('T053','Amputação traumática de ambos os pés'),
('T054','Amputação traumática de um pé e outra perna [qualquer nível'),
('T055','Amputação traumática de ambas as pernas [qualquer nível]'),
('T056','Amputação traumática de membros superiores e inferiores'),
('T058','Amputações traumáticas envolvendo outras combinações de regiões do corpo'),
('T059','Amputações traumáticas múltiplas não especificadas'),
('T060','Traumatismos de cérebro e nervos cranianos com traumatismos de nervos e da medula espinhal ao nível do pescoço'),
('T061','Traumatismos de nervos e da medula espinhal envolvendo outras regiões múltiplas do corpo'),
('T062','Traumatismos de nervos envolvendo regiões múltiplas do corpo'),
('T063','Traumatismos de vasos sangüíneos envolvendo regiões múltiplas do corpo'),
('T064','Traumatismos de músculos e de tendões envolvendo regiões múltiplas do corpo'),
('T065','Traumatismos de órgãos intratorácicos com órgãos intra-abdominais e pélvicos'),
('T068','Outros traumatismos especificados envolvendo regiões múltiplas do corpo'),
('T07','Traumatismos múltiplos não especificados'),
('T08','Fratura da coluna'),
('T090','Traumatismo superficial do tronco'),
('T091','Ferimento do tronco'),
('T092','Luxação'),
('T093','Traumatismo de medula espinhal'),
('T094','Traumatismo de nervos'),
('T095','Traumatismo de músculo e tendão não especificados do tronco'),
('T096','Amputação traumática do tronco'),
('T098','Outros traumatismos especificados do tronco'),
('T099','Traumatismo não especificado do tronco'),
('T10','Fratura do membro superior'),
('T110','Traumatismo superficial do membro superior'),
('T111','Ferimento do membro superior'),
('T112','Luxação'),
('T113','Traumatismo de nervo não especificado do membro superior'),
('T114','Traumatismo de vaso sangüíneo não especificado'),
('T115','Traumatismo de músculo e tendão não especificado do membro superior'),
('T116','Amputação traumática do membro superior'),
('T118','Outros traumatismos especificados do membro superior nível não especificado'),
('T119','Traumatismo não especificado do membro superior nível não especificado'),
('T12','Fratura do membro inferior'),
('T130','Traumatismo superficial de membro inferior'),
('T131','Ferimento de membro inferior'),
('T132','Luxação'),
('T133','Traumatismo de nervo não especificado de membro inferior'),
('T134','Traumatismo de vaso sangüíneo não especificado de membro inferior'),
('T135','Traumatismo de músculo e tendão não especificado de membro inferior'),
('T136','Amputação traumática de membro inferior'),
('T138','Outros traumatismos especificados de membro inferior'),
('T139','Traumatismo não especificado do membro inferior'),
('T140','Traumatismo superficial de região não especificada do corpo'),
('T141','Ferimento de região não especificada do corpo'),
('T142','Fratura de região não especificada do corpo'),
('T143','Luxação'),
('T144','Traumatismo de nervo(s) de região não especificada do corpo'),
('T145','Traumatismo de vaso(s) sangüíneo(s) de região não especificada do corpo'),
('T146','Traumatismo de músculos e tendões de região não especificada do corpo'),
('T147','Traumatismo por esmagamento e amputação traumática de regiões não especificadas do corpo'),
('T148','Outros traumatismos de região não especificada do corpo'),
('T149','Traumatismo não especificado'),
('T150','Corpo estranho na córnea'),
('T151','Corpo estranho no saco conjuntival'),
('T158','Corpo estranho em outros locais e em locais múltiplos da parte externa do olho'),
('T159','Corpo estranho em parte não especificada da região externa do olho'),
('T16','Corpo estranho no ouvido'),
('T170','Corpo estranho no seio nasal'),
('T171','Corpo estranho na narina'),
('T172','Corpo estranho na faringe'),
('T173','Corpo estranho na laringe'),
('T174','Corpo estranho na traquéia'),
('T175','Corpo estranho no brônquio'),
('T178','Corpo estranho em outras partes e partes múltiplas do trato respiratório'),
('T179','Corpo estranho no trato respiratório'),
('T180','Corpo estranho na boca'),
('T181','Corpo estranho no esôfago'),
('T182','Corpo estranho no estômago'),
('T183','Corpo estranho no intestino delgado'),
('T184','Corpo estranho no cólon'),
('T185','Corpo estranho no ânus e reto'),
('T188','Corpo estranho em outras partes e partes múltiplas do aparelho digestivo'),
('T189','Corpo estranho em parte não especificada do aparelho digestivo'),
('T190','Corpo estranho na uretra'),
('T191','Corpo estranho na bexiga'),
('T192','Corpo estranho na vulva e vagina'),
('T193','Corpo estranho no útero [qualquer parte]'),
('T198','Corpo estranho em outras partes e partes múltiplas do trato geniturinário'),
('T199','Corpo estranho no trato geniturinário'),
('T200','Queimadura da cabeça e do pescoço'),
('T201','Queimadura de primeiro grau da cabeça e do pescoço'),
('T202','Queimadura de segundo grau da cabeça e do pescoço'),
('T203','Queimadura de terceiro grau da cabeça e do pescoço'),
('T204','Corrosão da cabeça e do pescoço'),
('T205','Corrosão de primeiro grau da cabeça e do pescoço'),
('T206','Corrosão de segundo grau da cabeça e do pescoço'),
('T207','Corrosão de terceiro grau da cabeça e do pescoço'),
('T210','Queimadura do tronco'),
('T211','Queimadura de primeiro grau do tronco'),
('T212','Queimadura de segundo grau do tronco'),
('T213','Queimadura de terceiro grau do tronco'),
('T214','Corrosão do tronco'),
('T215','Corrosão de primeiro grau do tronco'),
('T216','Corrosão de segundo grau do tronco'),
('T217','Corrosão de terceiro grau do tronco'),
('T220','Queimadura do ombro e do membro superior'),
('T221','Queimadura de primeiro grau do ombro e do membro superior'),
('T222','Queimadura de segundo grau do ombro e do membro superior'),
('T223','Queimadura de terceiro grau do ombro e do membro superior'),
('T224','Corrosão do ombro e do membro superior'),
('T225','Corrosão de primeiro grau do ombro e do membro superior'),
('T226','Corrosão de segundo grau do ombro e do membro superior'),
('T227','Corrosão de terceiro grau do ombro e do membro superior'),
('T230','Queimadura do punho e da mão'),
('T231','Queimadura de primeiro grau do punho e da mão'),
('T232','Queimadura de segundo grau do punho e da mão'),
('T233','Queimadura de terceiro grau do punho e da mão'),
('T234','Corrosão do punho e da mão'),
('T235','Corrosão de primeiro grau do punho e da mão'),
('T236','Corrosão de segundo grau do punho e da mão'),
('T237','Corrosão de terceiro grau do punho e da mão'),
('T240','Queimadura do quadril e membro inferior'),
('T241','Queimadura de primeiro grau do quadril e do membro inferior'),
('T242','Queimadura de segundo grau do quadril e do membro inferior'),
('T243','Queimadura de terceiro grau do quadril e do membro inferior'),
('T244','Corrosão do quadril e do membro inferior'),
('T245','Corrosão de primeiro grau do quadril e do membro inferior'),
('T246','Corrosão de segundo grau do quadril e do membro inferior'),
('T247','Corrosão de terceiro grau do quadril e do membro inferior'),
('T250','Queimadura do tornozelo e do pé'),
('T251','Queimadura de primeiro grau do tornozelo e do pé'),
('T252','Queimadura de segundo grau do tornozelo e do pé'),
('T253','Queimadura de terceiro grau do tornozelo e do pé'),
('T254','Corrosão do tornozelo e do pé'),
('T255','Corrosão de primeiro grau do tornozelo e do pé'),
('T256','Corrosão de segundo grau do tornozelo e do pé'),
('T257','Corrosão de terceiro grau do tornozelo e do pé'),
('T260','Queimadura da pálpebra e da região periocular'),
('T261','Queimadura da córnea e do saco conjuntival'),
('T262','Queimadura com resultante ruptura e destruição do globo ocular'),
('T263','Queimadura de outras partes do olho e anexos'),
('T264','Queimadura do olho e anexos'),
('T265','Corrosão da pálpebra e da região periocular'),
('T266','Corrosão da córnea e do saco conjuntival'),
('T267','Corrosão com resultante ruptura e destruição do globo ocular'),
('T268','Corrosão de outras partes do olho e anexos'),
('T269','Corrosão do olho e anexos'),
('T270','Queimadura da laringe e traquéia'),
('T271','Queimadura da laringe'),
('T272','Queimadura de outras partes do trato respiratório'),
('T273','Queimadura do trato respiratório'),
('T274','Corrosão da laringe e traquéia'),
('T275','Corrosão da laringe'),
('T276','Corrosão de outras partes do trato respiratório'),
('T277','Corrosão do trato respiratório'),
('T280','Queimadura da boca e da faringe'),
('T281','Queimadura do esôfago'),
('T282','Queimadura de outras partes do trato alimentar'),
('T283','Queimadura dos órgãos geniturinários internos'),
('T284','Queimadura de outros órgãos internos e dos não especificados'),
('T285','Corrosão da boca e faringe'),
('T286','Corrosão do esôfago'),
('T287','Corrosão de outras partes do trato alimentar'),
('T288','Corrosão de órgãos geniturinários internos'),
('T289','Corrosão de outros órgãos internos e dos não especificados'),
('T290','Queimaduras múltiplas'),
('T291','Queimaduras múltiplas'),
('T292','Queimaduras múltiplas'),
('T293','Queimaduras múltiplas'),
('T294','Corrosões múltiplas'),
('T295','Corrosões múltiplas'),
('T296','Corrosões múltiplas'),
('T297','Corrosões múltiplas'),
('T300','Queimadura'),
('T301','Queimadura de primeiro grau'),
('T302','Queimadura de segundo grau'),
('T303','Queimadura de terceiro grau'),
('T304','Corrosão'),
('T305','Corrosão de primeiro grau'),
('T306','Corrosão de segundo grau'),
('T307','Corrosão de terceiro grau'),
('T310','Queimaduras envolvendo menos de 10% da superfície corporal'),
('T311','Queimaduras envolvendo de 10 - 19% da superfície corporal'),
('T312','Queimaduras envolvendo de 20 - 29% da superfície corporal'),
('T313','Queimaduras envolvendo de 30 - 39% da superfície corporal'),
('T314','Queimaduras envolvendo de 40 - 49% da superfície corporal'),
('T315','Queimaduras envolvendo de 50 - 59% da superfície corporal'),
('T316','Queimaduras envolvendo de 60 - 69% da superfície corporal'),
('T317','Queimaduras envolvendo de 70 - 79% da superfície corporal'),
('T318','Queimaduras envolvendo de 80 - 89% da superfície corporal'),
('T319','Queimaduras envolvendo 90% ou mais da superfície corporal'),
('T320','Corrosões envolvendo menos de 10% da superfície corporal'),
('T321','Corrosões envolvendo 10 - 19% da superfície corporal'),
('T322','Corrosões envolvendo 20 - 29% da superfície corporal'),
('T323','Corrosões envolvendo 30 - 39% da superfície corporal'),
('T324','Corrosões envolvendo 40 - 49% da superfície corporal'),
('T325','Corrosões envolvendo 50 - 59% da superfície corporal'),
('T326','Corrosões envolvendo 60 - 69% da superfície corporal'),
('T327','Corrosões envolvendo 70 - 79% da superfície corporal'),
('T328','Corrosões envolvendo 80 - 89% da superfície corporal'),
('T329','Corrosões envolvendo 90% ou mais da superfície corporal'),
('T330','Geladura superficial da cabeça'),
('T331','Geladura superficial do pescoço'),
('T332','Geladura superficial do tórax'),
('T333','Geladura superficial da parede abdominal'),
('T334','Geladura superficial do braço'),
('T335','Geladura superficial do punho e da mão'),
('T336','Geladura superficial do quadril e da coxa'),
('T337','Geladura superficial do joelho e da perna'),
('T338','Geladura superficial do tornozelo e do pé'),
('T339','Geladura superficial de outros locais e de locais não especificados'),
('T340','Geladura, com necrose de tecidos, da cabeça'),
('T341','Geladura, com necrose de tecidos, do pescoço'),
('T342','Geladura, com necrose de tecidos, do tórax'),
('T343','Geladura, com necrose de tecidos, da parede abdominal, parte inferior do dorso e da pelve'),
('T344','Geladura, com necrose de tecidos, do braço'),
('T345','Geladura, com necrose de tecidos, do punho e da mão'),
('T346','Geladura, com necrose de tecidos, do quadril e da coxa'),
('T347','Geladura, com necrose de tecidos, do joelho e da perna'),
('T348','Geladura, com necrose de tecidos, do tornozelo e do pé'),
('T349','Geladura, com necrose de tecidos, de localização não especificada'),
('T350','Geladura superficial envolvendo múltiplas partes do corpo'),
('T351','Geladura, com necrose de tecidos, de múltiplas partes do corpo'),
('T352','Geladura, de grau não especificado, da cabeça e do pescoço'),
('T353','Geladura, de grau não especificado, do tórax, abdome, parte inferior do dorso e da pelve'),
('T354','Geladura, de grau não especificado, do membro superior'),
('T355','Geladura, de grau não especificado, do membro inferior'),
('T356','Geladura, de grau não especificado, de múltiplas partes do corpo'),
('T357','Geladura, de grau não especificado, de localização não especificada'),
('T360','Intoxicação por penicilinas'),
('T361','Intoxicação por cefalosporinas e outras betalactaminas'),
('T362','Intoxicação pelo grupo do cloranfenicol'),
('T363','Intoxicação por macrolídios'),
('T364','Intoxicação por tetraciclinas'),
('T365','Intoxicação por aminoglicosídeos'),
('T366','Intoxicação por rifamicinas'),
('T367','Intoxicação por antibióticos antifúngicos administrados por via sistêmica'),
('T368','Intoxicação por outros antibióticos sistêmicos'),
('T369','Intoxicação por antibióticos sistêmicos não especificados'),
('T370','Intoxicação por sulfonamidas'),
('T371','Intoxicação por drogas antimicobacterianas'),
('T372','Intoxicação por antimaláricos e drogas que atuam sobre outros protozoários do sangue'),
('T373','Intoxicação por outros medicamentos antiprotozoários'),
('T374','Intoxicação por anti-helmínticos'),
('T375','Intoxicação por drogas antivirais'),
('T378','Intoxicação por outros agentes antiinfecciosos e antiparasitários especificados'),
('T379','Intoxicação por agentes antiinfecciosos e antiparasitários sistêmicos não especificados'),
('T380','Intoxicação por glicocorticóides e análogos sintéticos'),
('T381','Intoxicação por hormônios tireoidianos e seus derivados'),
('T382','Intoxicação por medicamentos antitireoidianos'),
('T383','Intoxicação por insulina e drogas hipoglicemiantes orais [antidiabéticos]'),
('T384','Intoxicação por anticoncepcionais orais'),
('T385','Intoxicação por outros estrógenos e progestágenos'),
('T386','Intoxicação por antigonadotrofinas'),
('T387','Intoxicação por andrógenos e anabolizantes congêneres'),
('T388','Intoxicação por outros hormônios e substitutos sintéticos'),
('T389','Intoxicação por outros antagonistas hormonais'),
('T390','Intoxicação por salicilatos'),
('T391','Intoxicação por derivados do 4-aminofenol'),
('T392','Intoxicação por derivados pirazolônicos'),
('T393','Intoxicação por outros antiinflamatórios não esteróides'),
('T394','Intoxicação por anti-reumáticos não classificados em outra parte'),
('T398','Intoxicação por outros analgésicos não opiáceos e antipiréticos não classificados em outra parte'),
('T399','Intoxicação por analgésico não-opiáceo'),
('T400','Intoxicação por ópio'),
('T401','Intoxicação por heroína'),
('T402','Intoxicação por outros opiáceos'),
('T403','Intoxicação por metadona'),
('T404','Intoxicação por outros narcóticos sintéticos'),
('T405','Intoxicação por cocaína'),
('T406','Intoxicação por outros narcóticos e os não especificados'),
('T407','Intoxicação por cannabis (derivados)'),
('T408','Intoxicação por lisergida [LSD]'),
('T409','Intoxicação por outros psicodislépticos e os não especificados [alucinógenos]'),
('T410','Intoxicação por anestésicos inalatórios'),
('T411','Intoxicação por anestésicos intravenosos'),
('T412','Intoxicação por outros anestésicos gerais e os não especificados'),
('T413','Intoxicação por anestésicos locais'),
('T414','Intoxicação por anestésico não especificado'),
('T415','Intoxicação por gases terapêuticos'),
('T420','Intoxicação por derivados da hidantoína'),
('T421','Intoxicação por iminostilbenos'),
('T422','Intoxicação por succinimidas e oxazolidinadionas'),
('T423','Intoxicação por barbitúricos'),
('T424','Intoxicação por benzodiazepinas'),
('T425','Intoxicação por antiepiléticos em associação'),
('T426','Intoxicação por outras drogas antiepilépticas e sedativos-hipnóticos'),
('T427','Intoxicação por drogas antiepilépticos'),
('T428','Intoxicação por drogas antiparkinsonianos e outros depressores centrais do tônus muscular'),
('T430','Intoxicação por antidepressivos tricíclicos e tetracíclicos'),
('T431','Intoxicação por antidepressivos inibidores da monoaminooxidase (MAO)'),
('T432','Intoxicação por outros antidepressivos e os não especificados'),
('T433','Intoxicação por antipsicóticos e neurolépticos derivados da fenotiazina'),
('T434','Intoxicação por neurolépticos do tipo butirofenona e tioxanteno'),
('T435','Intoxicação por outros antipsicóticos e neurolépticos e os não especificados'),
('T436','Intoxicação por psicoestimulantes que potencialmente podem provocar dependência'),
('T438','Intoxicação por outras drogas psicotrópicas não classificadas em outra parte'),
('T439','Intoxicação por droga psicotrópica não especificada'),
('T440','Intoxicação por agentes anticolinesterase'),
('T441','Intoxicação por outros agentes parassimpaticomiméticos [colinérgicos]'),
('T442','Intoxicação por bloqueadores ganglionares não classificados em outra parte'),
('T443','Intoxicação por outros parassimpaticolíticos [anticolinérgicos e antimuscarínicos] e espasmolíticos não classificados em outra parte'),
('T444','Intoxicação por agonistas principalmente alfa-adrenorreceptores não classificados em outra parte'),
('T445','Intoxicação por agonistas principalmente beta-adrenorreceptores não classificados em outra parte'),
('T446','Intoxicação por antagonistas alfa-adrenorreceptores não classificados em outra parte'),
('T447','Intoxicação por antagonistas beta-adrenorreceptores não classificados em outra parte'),
('T448','Intoxicação por bloqueadores neuronais adrenérgicos e de ação central'),
('T449','Intoxicação por outras drogas que afetam principalmente o sistema nervoso autônomo e as não especificadas'),
('T450','Intoxicação por drogas antialérgicas e antieméticas'),
('T451','Intoxicação por drogas antineoplásicas e imunomupressoras'),
('T452','Intoxicação por vitaminas'),
('T453','Intoxicação por enzimas'),
('T454','Intoxicação por ferro e seus compostos'),
('T455','Intoxicação por anticoagulantes'),
('T456','Intoxicação por drogas que afetam a fibrinólise'),
('T457','Intoxicação por antagonistas de anticoagulantes'),
('T458','Intoxicação por outras substâncias primariamente sistêmicas e hematológicas'),
('T459','Intoxicação por substância essencialmente sistêmica e hematológica não especificada'),
('T460','Intoxicação por glicosídeos estimulantes do coração e substâncias de ação semelhante'),
('T461','Intoxicação por bloqueadores dos canais de cálcio'),
('T462','Intoxicação por outras drogas antidisrítmicas não classificadas em outra parte'),
('T463','Intoxicação por vasodilatadores coronarianos'),
('T464','Intoxicação por inibidores da enzima de conversão da angiotensina'),
('T465','Intoxicação por outras drogas anti-hipertensivas não classificadas em outra parte'),
('T466','Intoxicação por drogas antihiperlipêmicas e antiarterioscleróticas'),
('T467','Intoxicação por vasodilatadores periféricos'),
('T468','Intoxicação por drogas antivaricosas'),
('T469','Intoxicação por outras substâncias e as não especificadas que agem essencialmente sobre o aparelho circulatório'),
('T470','Intoxicação por antagonistas dos receptores H2 da histamina'),
('T471','Intoxicação por outros antiácidos e drogas que inibem a secreção gástrica'),
('T472','Intoxicação por laxativos estimulantes'),
('T473','Intoxicação por laxativos salinos e osmóticos'),
('T474','Intoxicação por outros laxativos'),
('T475','Intoxicação por digestivos'),
('T476','Intoxicação por drogas antidiarréicas'),
('T477','Intoxicação por eméticos'),
('T478','Intoxicação por outras substâncias que atuam primariamente sobre o aparelho gastrintestinal'),
('T479','Intoxicação por substância não especificada que atua primariamente sobre o aparelho gastrointestinal'),
('T480','Intoxicação por drogas ocitócicas'),
('T481','Intoxicação por relaxantes musculares esqueléticos [bloqueadores neuromusculares]'),
('T482','Intoxicação por outras substâncias e as não especificadas que atuam sobre os músculos'),
('T483','Intoxicação por antitussígenos'),
('T484','Intoxicação por expectorantes'),
('T485','Intoxicação por drogas anti-resfriado'),
('T486','Intoxicação por antiasmáticos não classificados em outra parte'),
('T487','Intoxicação por outras substâncias e as não especificadas que atuam primariamente sobre o aparelho respiratório'),
('T490','Intoxicação por antifúngicos'),
('T491','Intoxicação por antipruriginosos'),
('T492','Intoxicação por adstringentes e detergentes de uso local'),
('T493','Intoxicação por emolientes'),
('T494','Intoxicação por ceratolíticos'),
('T495','Intoxicação por drogas e preparações de uso oftalmológico'),
('T496','Intoxicação por drogas e preparações de uso otorrinolaringológico'),
('T497','Intoxicação por drogas dentárias de uso tópico'),
('T498','Intoxicação por outras drogas de uso tópico'),
('T499','Intoxicação por preparado de uso tópico'),
('T500','Intoxicação por mineralocorticóides e seus antagonistas'),
('T501','Intoxicação por diuréticos de alça'),
('T502','Intoxicação por inibidores da anidrase carbônica'),
('T503','Intoxicação por produtos que agem sobre o equilíbrio eletrolítico'),
('T504','Intoxicação por drogas que agem sobre o metabolismo do ácido úrico'),
('T505','Intoxicação por inibidores do apetite'),
('T506','Intoxicação por antídotos e quelantes não classificados em outra parte'),
('T507','Intoxicação por analépticos e antagonistas dos receptores de opiáceos'),
('T508','Intoxicação por agentes de diagnóstico'),
('T509','Intoxicação por outras drogas'),
('T510','Efeito tóxico do etanol'),
('T511','Efeito tóxico do metanol'),
('T512','Efeito tóxico do 2-propanol'),
('T513','Efeito tóxico do óleo de fusel'),
('T518','Efeito tóxico de outros álcoois'),
('T519','Efeito tóxico de álcool não especificado'),
('T520','Efeito tóxico de derivados do petróleo'),
('T521','Efeito tóxico do benzeno'),
('T522','Efeito tóxico de homólogos do benzeno'),
('T523','Efeito tóxico de glicóis'),
('T524','Efeito tóxico de cetonas'),
('T528','Efeito tóxico de outros solventes orgânicos'),
('T529','Efeito tóxico de solvente orgânico não especificado'),
('T530','Efeito tóxico do tetracloreto de carbono'),
('T531','Efeito tóxico do clorofórmio'),
('T532','Efeito tóxico do tricloroetileno'),
('T533','Efeito tóxico do tetracloroetileno'),
('T534','Efeito tóxico do diclorometano'),
('T535','Efeito tóxico do clorofluorcarbono'),
('T536','Efeito tóxico de outros derivados halogênicos de hidrocarbonetos alifáticos'),
('T537','Efeito tóxico de derivados halogênicos de hidrocarbonetos aromáticos'),
('T539','Efeito tóxico de derivados halogênicos de hidrocarbonetos alifáticos e aromáticos não especificados'),
('T540','Efeito tóxico do fenol e homólogos do fenol'),
('T541','Efeito tóxico de outros compostos corrosivos orgânicos'),
('T542','Efeito tóxico de ácidos corrosivos e substâncias semelhantes'),
('T543','Efeito tóxico de bases (álcalis) cáusticas(os) e substâncias semelhantes'),
('T549','Efeito tóxico de substância corrosiva não especificada'),
('T55','Efeito tóxico de sabões e detergentes'),
('T560','Efeito tóxico do chumbo e seus compostos'),
('T561','Efeito tóxico do mercúrio e seus compostos'),
('T562','Efeito tóxico do cromo e seus compostos'),
('T563','Efeito tóxico do cádmio e seus compostos'),
('T564','Efeito tóxico do cobre e seus compostos'),
('T565','Efeito tóxico do zinco e seus compostos'),
('T566','Efeito tóxico do estanho e seus compostos'),
('T567','Efeito tóxico do berilo e seus compostos'),
('T568','Efeito tóxico de outros metais'),
('T569','Efeito tóxico de metal'),
('T570','Efeito tóxico do arsênico e seus compostos'),
('T571','Efeito tóxico do fósforo e seus compostos'),
('T572','Efeito tóxico do manganês e seus compostos'),
('T573','Efeito tóxico do cianeto de hidrogênio (ácido cianídrico)'),
('T578','Efeito tóxico de outras substâncias inorgânicas especificadas'),
('T579','Efeito tóxico de substância inorgânica não especificada'),
('T58','Efeito tóxico do monóxido de carbono'),
('T590','Efeito tóxico de óxidos de nitrogênio'),
('T591','Efeito tóxico do dióxido de enxofre'),
('T592','Efeito tóxico de formaldeído'),
('T593','Efeito tóxico do gás lacrimogêneo'),
('T594','Efeito tóxico do cloro gasoso'),
('T595','Efeito tóxico do fluoreto gasoso e ácido fluorídrico'),
('T596','Efeito tóxico do ácido sulfídrico'),
('T597','Efeito tóxico do dióxido de carbono'),
('T598','Efeito tóxico de outros gases'),
('T599','Efeito tóxico de gases'),
('T600','Efeito tóxico de inseticidas organofosforados e carbamatos'),
('T601','Efeito tóxico de inseticidas halogenados'),
('T602','Efeito tóxico de outros inseticidas'),
('T603','Efeito tóxico de herbicidas e fungicidas'),
('T604','Efeito tóxico de rodenticidas'),
('T608','Efeito tóxico de outros pesticidas'),
('T609','Efeito tóxico de pesticida não especificado'),
('T610','Intoxicação pelo peixe ciguatera'),
('T611','Intoxicação por peixes escombrídeos'),
('T612','Outras intoxicações por peixes e mariscos'),
('T618','Efeito tóxico de outros frutos do mar'),
('T619','Efeito tóxico de frutos do mar não especificados'),
('T620','Efeito tóxico de ingestão de cogumelos'),
('T621','Efeito tóxico de ingestão de frutos'),
('T622','Efeito tóxico de ingestão de outras (partes de) plantas'),
('T628','Efeito tóxico de outras substâncias nocivas ingeridas como alimento'),
('T629','Efeito tóxico de substâncias nocivas ingeridas como alimento'),
('T630','Efeito tóxico do veneno de serpente'),
('T631','Efeito tóxico do veneno de outros répteis'),
('T632','Efeito tóxico do veneno de escorpião'),
('T633','Efeito tóxico do veneno de aranha'),
('T634','Efeito tóxico do veneno de outros artrópodes'),
('T635','Efeito tóxico de contato com peixe'),
('T636','Efeito tóxico de contato com outros animais marinhos'),
('T638','Efeito tóxico de contato com outros animais venenosos'),
('T639','Efeito tóxico de contato com animal venenoso não especificado'),
('T64','Efeito tóxico da aflatoxina e de outras micotoxinas contaminantes de alimentos'),
('T650','Efeito tóxico de cianetos'),
('T651','Efeito tóxico da estricnina e seus sais'),
('T652','Efeito tóxico do tabaco e da nicotina'),
('T653','Efeito tóxico de nitroderivados e aminoderivados do benzeno e seus homólogos'),
('T654','Efeito tóxico do dissulfeto de carbono'),
('T655','Efeito tóxico da nitroglicerina e outros ácidos e ésteres nítricos'),
('T656','Efeito tóxico de tinturas e corantes'),
('T658','Efeito tóxico de outras substâncias especificadas'),
('T659','Efeito tóxico de substância não especificada'),
('T66','Efeitos não especificados de radiação'),
('T670','Golpe de calor e insolação'),
('T671','Síncope devida ao calor'),
('T672','Cãibras devidas ao calor'),
('T673','Exaustão devida ao calor e à perda hídrica'),
('T674','Exaustão devida ao calor e à perda de sal'),
('T675','Exaustão devida ao calor'),
('T676','Fadiga transitória devida ao calor'),
('T677','Edema devido ao calor'),
('T678','Outros efeitos do calor e da luz'),
('T679','Efeito do calor e da luz não especificado'),
('T68','Hipotermia'),
('T690','Mão e pé de imersão'),
('T691','Congelamento [chilblains]'),
('T698','Outros efeitos especificados de temperatura reduzida'),
('T699','Efeito não especificado de temperatura reduzida'),
('T700','Otite barotraumática'),
('T701','Sinusite barotraumática'),
('T702','Outros efeitos das grandes altitude e os não especificados'),
('T703','Mal dos caixões [doença de descompressão]'),
('T704','Efeito dos fluidos em alta pressão'),
('T708','Outros efeitos da pressão atmosférica ou da pressão da água'),
('T709','Efeitos não especificados da pressão atmosférica ou da pressão da água'),
('T71','Asfixia'),
('T730','Efeitos da fome'),
('T731','Efeitos da sede'),
('T732','Exaustão devida às intempéries'),
('T733','Exaustão devido a um esforço intenso'),
('T738','Outros efeitos de privação'),
('T739','Efeito não especificado de privação'),
('T740','Abandono'),
('T741','Sevícias físicas'),
('T742','Abuso sexual'),
('T743','Abuso psicológico'),
('T748','Outras síndromes especificadas de maus tratos'),
('T749','Síndrome não especificada de maus tratos'),
('T750','Efeitos do raio'),
('T751','Afogamento e submersão não mortal'),
('T752','Efeitos da vibração'),
('T753','Doença causada pelo movimento'),
('T754','Efeitos da corrente elétrica'),
('T758','Outros efeitos especificados de causas externas'),
('T780','Choque anafilático devido à intolerância alimentar'),
('T781','Outras reações de intolerância alimentar não classificadas em outra parte'),
('T782','Choque anafilático não especificado'),
('T783','Edema angioneurótico'),
('T784','Alergia não especificada'),
('T788','Outros efeitos adversos não classificados em outra parte'),
('T789','Efeito adverso não especificado'),
('T790','Embolia gasosa (traumática)'),
('T791','Embolia gordurosa (traumática)'),
('T792','Hemorragia traumática secundária e recidivante'),
('T793','Infecção pós-traumática de ferimento não classificada em outra parte'),
('T794','Choque traumático'),
('T795','Anúria traumática'),
('T796','Isquemia muscular traumática'),
('T797','Enfisema subcutâneo de origem traumática'),
('T798','Outras complicações precoces de traumatismo'),
('T799','Complicação precoce não especificada de traumatismo'),
('T800','Embolia aérea subseqüentes à infusão'),
('T801','Complicações vasculares subseqüentes à infusão'),
('T802','Infecções subseqüentes à infusão'),
('T803','Reação de incompatibilidade ABO'),
('T804','Reação de incompatibilidade Rh'),
('T805','Choque anafilático devido a soro'),
('T806','Outras reações ao soro'),
('T808','Outras complicações subseqüentes à infusão'),
('T809','Complicação não especificada subseqüente à infusão'),
('T810','Hemorragia e hematoma complicando procedimento não classificado em outra parte'),
('T811','Choque durante ou resultante de procedimento não classificado em outra parte'),
('T812','Perfuração e laceração acidentais durante um procedimento não classificado em outra parte'),
('T813','Deiscência de ferida cirúrgica não classificada em outra parte'),
('T814','Infecção subseqüente a procedimento não classificada em outra parte'),
('T815','Corpo estranho deixado acidentalmente em cavidade corporal ou em ferida operatória subseqüente a procedimento'),
('T816','Reação aguda à substância estranha deixada acidentalmente durante um procedimento'),
('T817','Complicações vasculares subseqüentes a um procedimento não classificado em outra parte'),
('T818','Outras complicações de procedimentos não classificadas em outra parte'),
('T819','Complicação não especificada de procedimento'),
('T820','Complicação mecânica de prótese valvular cardíaca'),
('T821','Complicação mecânica de dispositivo eletrônico cardíaco'),
('T822','Complicação mecânica de enxerto de ponte coronária e implantes de valvas'),
('T823','Complicações mecânicas de outros enxertos vasculares'),
('T824','Complicação mecânica de cateter vascular de diálise'),
('T825','Complicações mecânicas de outros dispositivos e implantes cardiovasculares'),
('T826','Infecção e reação inflamatórias devidas à prótese valvular cardíaca'),
('T827','Infecção e reação inflamatórias devidas a outros dispositivos'),
('T828','Outras complicações de dispositivos protéticos'),
('T829','Complicações não especificada de dispositivo protético'),
('T830','Complicação mecânica de cateter (de demora) urinário'),
('T831','Complicação mecânica de outros dispositivos e implantes urinários'),
('T832','Complicação mecânica de enxerto de órgão urinário'),
('T833','Complicação mecânica de dispositivo intra-uterino (anticoncepcional)'),
('T834','Complicação mecânica de outros dispositivos protéticos'),
('T835','Infecção e reação inflamatória devidas à dispositivo protético'),
('T836','Infecção e reação inflamatória devidas à dispositivo protético'),
('T838','Outras complicações de dispositivos protéticos'),
('T839','Complicação não especificada de prótese'),
('T840','Complicação mecânica de prótese articular interna'),
('T841','Complicação mecânica de dispositivo de fixação interna de ossos dos membros'),
('T842','Complicação mecânica de dispositivo de fixação interna de outros ossos'),
('T843','Complicação mecânica de outros dispositivos'),
('T844','Complicação mecânica de outros dispositivos'),
('T845','Infecção e reação inflamatória devidas à prótese articular interna'),
('T846','Infecção e reação inflamatória devidas a dispositivo de fixação interna [qualquer local]'),
('T847','Infecção e reação inflamatória devidas a outros dispositivos protéticos'),
('T848','Outras complicações de dispositivos protéticos'),
('T849','Complicação não especificada de dispositivo protético'),
('T850','Complicação mecânica de shunt ventricular (comunicação) intracraniano'),
('T851','Complicação mecânica de estimulador eletrônico implantado no sistema nervoso'),
('T852','Complicação mecânica de lente intraocular'),
('T853','Complicações mecânicas de outros dispositivos protéticos'),
('T854','Complicação mecânica de prótese e implante mamários'),
('T855','Complicação mecânica de dispositivos protéticos'),
('T856','Complicação mecânica de outros dispositivos protéticos'),
('T857','Infecção e reação inflamatória devida a outros dispositivos protéticos'),
('T858','Outras complicações de dispositivos protéticos'),
('T859','Complicação não especificada de outros dispositivos protéticos'),
('T860','Rejeição a transplante de medula óssea'),
('T861','Falência ou rejeição de transplante de rim'),
('T862','Falência ou rejeição de transplante de coração'),
('T863','Falência ou rejeição de transplante duplo de coração e pulmão'),
('T864','Falência ou rejeição de transplante de fígado'),
('T868','Outra insuficiência ou rejeição de outros órgãos ou tecidos transplantados'),
('T869','Falência e rejeição a transplante de órgão ou tecido não especificado'),
('T870','Complicações de reimplante (de parte) de extremidade superior'),
('T871','Complicações de reimplante (de parte) de extremidade inferior'),
('T872','Complicações de outras partes reimplantadas do corpo'),
('T873','Neuroma de coto da amputação'),
('T874','Infecção de coto da amputação'),
('T875','Necrose do coto da amputação'),
('T876','Outras complicações e as não especificadas do coto de amputação'),
('T880','Infecção subseqüente à imunização'),
('T881','Outras complicações subseqüentes à imunização não classificadas em outra parte'),
('T882','Choque devido à anestesia'),
('T883','Hipertermia maligna devida à anestesia'),
('T884','Entubação falha ou difícil'),
('T885','Outras complicações de anestesia'),
('T886','Choque anafilático devido a efeito adverso de droga ou medicamento corretos e administrados de maneira apropriada'),
('T887','Efeito adverso não especificado de droga ou medicamento'),
('T888','Outras complicações de cuidados médicos e cirúrgicos especificados não classificados em outra parte'),
('T889','Complicação não especificada de cuidados médicos e cirúrgicos'),
('T900','Seqüelas de traumatismo superficial da cabeça'),
('T901','Seqüelas de ferimento da cabeça'),
('T902','Seqüelas de fratura de crânio e de ossos da face'),
('T903','Seqüelas de traumatismo de nervos cranianos'),
('T904','Seqüelas de traumatismo do olho e da órbita'),
('T905','Seqüelas de traumatismo intracraniano'),
('T908','Seqüelas de outros traumatismos especificados da cabeça'),
('T909','Seqüelas de traumatismo não especificado da cabeça'),
('T910','Seqüelas de traumatismo superficial e ferimento do pescoço e do tronco'),
('T911','Seqüelas de fratura de coluna vertebral'),
('T912','Seqüelas de outra fratura do tórax e da pelve'),
('T913','Seqüelas de traumatismo de medula espinhal'),
('T914','Seqüelas de traumatismo de órgãos intratorácicos'),
('T915','Seqüelas de traumatismo de órgãos intra-abdominais e órgãos pélvicos'),
('T918','Seqüelas de outros traumatismos especificados do pescoço e do tronco'),
('T919','Seqüelas de traumatismo não especificado do pescoço e do tronco'),
('T920','Seqüelas de ferimento do membro superior'),
('T921','Seqüelas de fratura do braço'),
('T922','Seqüelas de fratura ao nível do punho e da mão'),
('T923','Seqüelas de luxação'),
('T924','Seqüelas de traumatismo de nervo de membro superior'),
('T925','Seqüelas de traumatismo de músculo e tendão do membro superior'),
('T926','Seqüelas de esmagamento e amputação traumática do membro superior'),
('T928','Seqüelas de outros traumatismos especificados do membro superior'),
('T929','Seqüelas de traumatismo não especificado do membro superior'),
('T930','Seqüelas de ferimento do membro inferior'),
('T931','Seqüelas de fratura do fêmur'),
('T932','Seqüelas de outras fraturas do membro inferior'),
('T933','Seqüelas de luxação'),
('T934','Seqüelas de traumatismo de nervo do membro inferior'),
('T935','Seqüelas de traumatismo de músculo e tendão do membro inferior'),
('T936','Seqüelas de esmagamento e amputação traumática do membro inferior'),
('T938','Seqüelas de outros traumatismos especificados do membro inferior'),
('T939','Seqüelas de traumatismo não especificado do membro inferior'),
('T940','Seqüelas de traumatismos envolvendo regiões múltiplas do corpo'),
('T941','Seqüelas de traumatismos não especificados por regiões do corpo'),
('T950','Seqüelas de queimadura'),
('T951','Seqüelas de queimadura'),
('T952','Seqüelas de queimadura'),
('T953','Seqüelas de queimadura'),
('T954','Seqüelas de queimadura e corrosão classificável só de acordo com a extensão da área corporal envolvida'),
('T958','Seqüelas de outra queimadura'),
('T959','Seqüelas de queimadura'),
('T96','Seqüelas de intoxicação por drogas'),
('T97','Seqüelas de efeitos tóxicos de substâncias de origem predominantemente não-medicinal'),
('T980','Seqüelas dos efeitos da penetração de corpo estranho através de orifício natural'),
('T981','Seqüelas em outros efeitos de causas externas e os não especificados'),
('T982','Seqüelas de algumas complicações precoces de traumatismos'),
('T983','Seqüelas de complicações dos cuidados médicos e cirúrgicos não classificados em outra parte'),
('V010','Pedestre traumatizado em colisão com um veículo a pedal - acidente não-de-trânsito'),
('V011','Pedestre traumatizado em colisão com um veículo a pedal - acidente de trânsito'),
('V019','Pedestre traumatizado em colisão com um veículo a pedal - acidente não especificado se de trânsito ou não de trânsito'),
('V020','Pedestre traumatizado em colisão com um veículo a motor de duas ou três rodas - acidente não-de-trânsito'),
('V021','Pedestre traumatizado em colisão com um veículo a motor de duas ou três rodas - acidente de trânsito'),
('V029','Pedestre traumatizado em colisão com um veículo a motor de duas ou três rodas - acidente não especificado se de trânsito ou não de trânsito'),
('V030','Pedestre traumatizado em colisão com um automóvel [carro]'),
('Z313','Outros métodos assistidos de fertilização'),
('Z314','Investigação e testes com relação à procriação'),
('Z315','Aconselhamento genético'),
('Z316','Aconselhamento geral sobre a procriação'),
('Z318','Outra medida especificada de procriação'),
('Z319','Medida procriativa não especificada'),
('Z320','Gravidez (ainda) não confirmada'),
('Z321','Gravidez confirmada'),
('Z33','Gravidez como achado casual'),
('Z340','Supervisão de primeira gravidez normal'),
('Z348','Supervisão de outra gravidez normal'),
('Z349','Supervisão de gravidez normal'),
('Z350','Supervisão de gravidez com história de esterilidade'),
('Z351','Supervisão de gravidez com história de aborto'),
('Z352','Supervisão de gravidez com outros antecedentes de procriação problemática'),
('Z353','Supervisão de gravidez com história de assistência pré-natal insuficiente'),
('Z354','Supervisão de gravidez com grande multiparidade'),
('Z355','Supervisão de primigesta idosa'),
('Z356','Supervisão de primigesta muito jovem'),
('Z357','Supervisão de gravidez de alto risco devido a problemas sociais'),
('Z358','Supervisão de outras gravidezes de alto risco'),
('Z359','Supervisão não especificada de gravidez de alto risco'),
('Z360','Rastreamento de anomalias cromossômicas'),
('Z361','Rastreamento pré-natal de taxa elevada de alfa-fetoproteínas'),
('Z362','Outros rastreamentos pré-natais por amniocentese'),
('Z363','Rastreamento pré-natal de malformações por ultrassom e outros meios físicos'),
('Z364','Rastreamento pré-natal do retardo de crescimento do feto por ultrassom e outros métodos físicos'),
('Z365','Rastreamento pré-natal de isoimunização'),
('Z368','Outros rastreamentos pré-natais'),
('Z369','Rastreamento pré-natal não especificado'),
('Z370','Nascimento único, nativivo [nado-vivo]'),
('Z371','Nascimento único, natimorto [feto-morto] '),
('Z372','Nascimento gemelar, gêmeos (ambos) nativivos [nado-vivos]'),
('Z373','Nascimento gemelar, um dos gêmeos, nativivo [nado-vivo], o outro, natimorto [feto-morto]'),
('Z374','Nascimento gemelar, gêmeos natimortos [feto-mortos]'),
('Z375','Outros nascimentos múltiplos, todos nativivos [nado-vivos]'),
('Z376','Outros nascimentos múltiplos, alguns nativivos [nado-vivos]'),
('Z377','Outros nascimentos múltiplos, todos natimortos [feto-mortos]'),
('Z379','Nascimento não especificado'),
('Z380','Criança única, nascida em hospital'),
('Z381','Criança única, nascida fora do hospital'),
('Z382','Criança única, não especificado quanto ao local de nascimento'),
('Z383','Gêmeos (duplos), nascidos em hospital'),
('Z384','Gêmeos (duplos), nascidos fora de hospital'),
('Z385','Gêmeos, não especificados quanto ao local de nascimento'),
('Z386','Outros nascimentos múltiplos, em hospital'),
('Z387','Outros nascimentos múltiplos, fora de hospital'),
('Z388','Outros nascimentos múltiplos, não especificados quanto ao local de nascimento'),
('Z390','Assistência e exame imediatamente após o parto'),
('Z391','Assistência e exame da mãe nutriz'),
('Z392','Seguimento pós-parto de rotina'),
('Z400','Cirurgia profilática para fatores de risco relacionados com neoplasias malignas'),
('Z408','Outra cirurgia profilática'),
('Z409','Cirurgia profilática não especificada'),
('Z410','Transplante de cabelo'),
('Z411','Outras intervenções de cirurgia plástica por razões estéticas'),
('Z412','Circuncisão ritual e de rotina'),
('Z413','Perfuração do lobo da orelha'),
('Z418','Outros procedimentos para outros propósitos exceto cuidados de saúde'),
('Z419','Procedimentos não especificado para outros propósitos exceto cuidados de saúde'),
('Z420','Seguimento envolvendo cirurgia plástica da cabeça e do pescoço'),
('Z421','Seguimento envolvendo cirurgia plástica de mama'),
('Z422','Seguimento envolvendo cirurgia plástica de outras partes do tronco'),
('Z423','Seguimento envolvendo cirurgia plástica das extremidades superiores'),
('Z424','Seguimento envolvendo cirurgia plástica das extremidades inferiores'),
('Z428','Seguimento envolvendo cirurgia plástica de outras partes do corpo'),
('Z429','Seguimento envolvendo cirurgia plástica não especificada'),
('Z430','Cuidados à traqueostomia'),
('Z431','Cuidados à gastrostomia'),
('Z432','Cuidados à ileostomia'),
('Z433','Cuidados à colostomia'),
('Z434','Cuidados a outros orifícios artificiais do tubo digestivo'),
('Z435','Cuidados à cistostomia'),
('Z436','Cuidados a outros orifícios artificiais das vias urinárias'),
('Z437','Cuidados à vagina artificial'),
('Z438','Cuidados a outros orifícios artificiais'),
('Z439','Cuidados a orifício artificial não especificado'),
('Z440','Colocação e ajustamento de braço artificial (parcial) (total)'),
('Z441','Colocação e ajustamento de perna artificial (parcial) (total)'),
('Z442','Colocação e ajustamento de olho artificial'),
('Z443','Colocação e ajustamento de prótese externa de mama'),
('Z448','Colocação e ajustamento de outros aparelhos de prótese externa'),
('Z449','Colocação e ajustamento de aparelho de prótese externa não especificado'),
('Z450','Ajustamento e manuseio de marca-passo cardíaco'),
('Z451','Ajustamento e manuseio de bomba de infusão'),
('Z452','Ajustamento e manuseio de dispositivo de acesso vascular'),
('Z453','Ajustamento e manuseio de dispositivo implantado de audição'),
('Z458','Ajustamento e manuseio de outros dispositivos implantados'),
('Z459','Ajustamento e manuseio de dispositivo implantado não especificado'),
('Z460','Colocação e ajustamento de óculos e lentes de contato'),
('Z461','Colocação e ajustamento de aparelho auditivo'),
('Z462','Colocação e ajustamento de outros aparelhos relacionados com o sistema nervoso e órgãos dos sentidos'),
('Z463','Colocação e ajustamento de dispositivo de prótese dentária'),
('Z464','Colocação e ajustamento de aparelho ortodôntico'),
('Z465','Colocação e ajustamento de ileostomia e de outros dispositivos intestinais'),
('Z466','Colocação e ajustamento de prótese urinária'),
('Z467','Colocação e ajustamento de aparelho ortopédico'),
('Z468','Colocação e ajustamento de outros aparelhos especificados'),
('Z469','Colocação e ajustamento de aparelho não especificado'),
('Z470','Seguimento envolvendo remoção de placa de fratura e outros dispositivos de fixação interna'),
('Z478','Outros seguimentos ortopédicos especificados'),
('Z479','Seguimento ortopédico não especificado'),
('Z480','Cuidados a curativos e suturas cirúrgicas'),
('Z488','Outro seguimento cirúrgico especificado'),
('Z489','Seguimento cirúrgico não especificado'),
('Z490','Cuidado preparatório para diálise'),
('Z491','Diálise extracorpórea'),
('Z492','Outras diálises'),
('Z500','Reabilitação cardíaca'),
('Z501','Outra fisioterapia'),
('Z502','Reabilitação de alcoólatra'),
('Z503','Reabilitação de toxicodependentes'),
('Z504','Psicoterapia'),
('Z505','Reabilitação da linguagem'),
('Z506','Treinamento ortóptico'),
('Z507','Terapia ocupacional e reabilitação vocacional não classificada em outra parte'),
('Z508','Cuidados envolvendo uso de outros procedimentos de reabilitação'),
('Z509','Cuidados envolvendo uso de procedimento de reabilitação não especificado'),
('Z510','Sessão de radioterapia'),
('Z511','Sessão de quimioterapia por neoplasia'),
('Z512','Outra quimioterapia'),
('Z513','Transfusão de sangue'),
('Z514','Cuidado preparatório para tratamento subsequente não classificado em outra parte'),
('Z515','Cuidado paliativo'),
('Z516','Dessensibilização a alérgenos'),
('Z518','Outro cuidado médico especificado'),
('Z519','Cuidado médico não especificado'),
('Z520','Doador de sangue'),
('Z521','Doador de pele'),
('Z522','Doador de osso'),
('Z523','Doador de medula óssea'),
('Z524','Doador de rim'),
('Z525','Doador de córnea'),
('Z526','Doador de fígado'),
('Z527','Doador de coração'),
('Z528','Doador de outros órgãos ou tecidos'),
('Z529','Doador de órgão ou tecido não especificado'),
('Z530','Procedimento não realizado devido à contra-indicação'),
('Z531','Procedimento não realizado devido à decisão do paciente por razões de crença ou grupo de pressão'),
('Z532','Procedimento não realizado devido à decisão do paciente por outras razões e as não especificadas'),
('Z538','Procedimento não realizado por outras razões'),
('Z539','Procedimento não realizado por razão não especificada'),
('Z540','Convalescença após cirurgia'),
('Z541','Convalescença após radioterapia'),
('Z542','Convalescença após quimioterapia'),
('Z543','Convalescença após psicoterapia'),
('Z544','Convalescença após tratamento de fratura'),
('Z547','Convalescença após tratamento combinado'),
('Z548','Convalescença após outro tratamento'),
('Z549','Convalescença após tratamento não especificado'),
('Z550','Analfabetismo e baixa escolaridade'),
('Z551','Escolarização não disponível e impossível'),
('Z552','Reprovação em exames'),
('Z553','Maus resultados escolares'),
('Z554','Má adaptação escolar e dificuldades com professores e colegas'),
('Z558','Outros problemas relacionados com a educação e com a alfabetização'),
('Z559','Problemas não especificados relacionados com a educação e com a alfabetização'),
('Z560','Desemprego não especificado'),
('Z561','Mudança de emprego'),
('Z562','Ameaça de perda de emprego'),
('Z563','Ritmo de trabalho penoso'),
('Z564','Desacordo com patrão e colegas de trabalho'),
('Z565','Má adaptação ao trabalho'),
('Z566','Outras dificuldades físicas e mentais relacionadas ao trabalho'),
('Z567','Outros problemas e os não especificados relacionados com o emprego'),
('Z570','Exposição ocupacional ao ruído'),
('Z571','Exposição ocupacional à radiação'),
('Z572','Exposição ocupacional à poeira (pó)'),
('Z573','Exposição ocupacional a outros contaminantes do ar'),
('Z574','Exposição ocupacional a agentes tóxicos na agricultura'),
('Z575','Exposição ocupacional a agentes tóxicos em outras indústrias'),
('Z576','Exposição ocupacional a temperaturas extremas'),
('Z577','Exposição ocupacional à vibração'),
('Z578','Exposição ocupacional a outros fatores de risco'),
('Z579','Exposição ocupacional a fator de risco não especificado'),
('Z580','Exposição ao ruído'),
('Z581','Exposição à poluição atmosférica'),
('Z582','Exposição à poluição da água'),
('Z583','Exposição à poluição do solo'),
('Z584','Exposição à radiação'),
('Z585','Exposição a outras poluições'),
('Z586','Água potável insuficiente'),
('Z587','Exposição à fumaça de tabaco'),
('Z588','Outros problemas relacionados com o ambiente físico'),
('Z589','Problema não especificado relacionado com o ambiente físico'),
('Z590','Falta de domicílio fixo'),
('Z591','Habitação inadequada'),
('Z592','Desacordo com vizinhos'),
('Z593','Problemas relacionados com a vida em instituição residencial'),
('Z594','Falta de alimentação adequada'),
('Z595','Pobreza extrema'),
('Z596','Baixo rendimento'),
('Z597','Seguro social e medidas de bem-estar social insuficientes'),
('Z598','Outros problemas relacionados com a habitação e com as circunstâncias econômicas'),
('Z599','Circunstâncias não especificadas econômicas ou de habitação'),
('Z600','Problemas de adaptação às transições do ciclo de vida'),
('Z601','Situação parental atípica'),
('Z602','Viver só'),
('Z603','Dificuldade de aculturação'),
('Z604','Exclusão e rejeição sociais'),
('Z605','Objeto de discriminação e perseguição percebidas'),
('Z608','Outros problemas relacionados com o meio social'),
('Z609','Problema não especificado relacionado com o meio social'),
('Z610','Perda de relação afetiva na infância'),
('Z611','Remoção do lar na infância'),
('Z612','Padrão alterado de relações familiares na infância'),
('Z613','Eventos que originam a perda de auto-estima na infância'),
('Z614','Problemas relacionados com abuso sexual alegado de uma criança por uma pessoa de dentro de seu grupo'),
('Z615','Problemas relacionados com abuso sexual alegado de uma criança por pessoa de fora de seu grupo'),
('Z616','Problemas relacionados com abuso físico alegado da criança'),
('Z617','Experiência pessoal amedrontadora na infância'),
('Z618','Outros eventos da vida pessoal negativos na infância'),
('Z619','Evento pessoal negativo não especificado na infância'),
('Z620','Supervisão e controle inadequado por parte dos pais'),
('Z621','Superproteção por parte dos pais'),
('Z622','Educação numa instituição'),
('Z623','Hostilidade com relação a uma criança'),
('Z624','Negligência emocional da criança'),
('Z625','Outros problemas relacionados com negligência na educação dos filhos'),
('Z626','Pressões não apropriadas por parte dos pais e outras falhas de educação'),
('Z628','Outros problemas especificados relacionados com a educação dos filhos'),
('Z629','Problema não especificado relacionado com a educação dos filhos'),
('Z630','Problemas nas relações com cônjuge ou parceiro'),
('Z631','Problemas nas relações com os pais ou com os sogros'),
('Z632','Suporte familiar inadequado'),
('Z633','Ausência de um dos membros da família'),
('Z634','Desaparecimento ou falecimento de um membro da família'),
('Z635','Rompimento da família por separação ou divórcio'),
('Z636','Parente dependente de cuidados'),
('Z637','Outros acontecimentos difíceis com incidência na família ou no lar'),
('Z638','Outros problemas especificados relacionados com o grupo primário de suporte'),
('Z639','Problema não especificado relacionado com o grupo primário de suporte'),
('Z640','Problemas relacionados com uma gravidez não desejada'),
('Z641','Problemas relacionados com multiparidade'),
('Z642','Procura e aceitação de intervenções físicas'),
('Z643','Procura e aceitação de intervenções comportamentais ou psicológicas conhecidas como perigosas ou nocivas'),
('Z644','Desacordo com conselheiros'),
('Z650','Condenação'),
('Z651','Prisão ou encarceramento'),
('Z652','Problemas ligados à libertação de prisão'),
('Z653','Problemas ligados à outras circunstâncias legais'),
('Z654','Vítima de crime ou de atos terroristas'),
('Z655','Exposição a catástrofe'),
('Z658','Outros problemas especificados relacionados com circunstâncias psicossociais'),
('Z659','Problemas relacionados com circunstâncias psicossociais não especificadas'),
('Z700','Acompanhamento relativo às atitudes em matéria de sexualidade'),
('Z701','Aconselhamento relativo ao comportamento e à orientação sexual do sujeito'),
('Z702','Aconselhamento relativo ao comportamento e à orientação sexual de um terceiro'),
('Z703','Aconselhamento relativo a preocupações associadas relacionadas com as atitudes'),
('Z708','Outros aconselhamentos em matéria de sexualidade'),
('Z709','Aconselhamento não especificado em matéria de sexualidade'),
('Z710','Pessoa que consulta no interesse de um terceiro'),
('Z711','Pessoa com medo de uma queixa para a qual não foi feito diagnóstico'),
('Z712','Pessoa que consulta para explicação de achados de exame'),
('Z713','Aconselhamento e supervisão dietéticos'),
('Z714','Aconselhamento e supervisão para abuso de álcool'),
('Z715','Aconselhamento e supervisão para abuso de drogas'),
('Z716','Aconselhamento para o abuso de fumo'),
('Z717','Aconselhamento a propósito do vírus da imunodeficiência humana [HIV]'),
('Z718','Outros aconselhamentos especificados'),
('Z719','Aconselhamento não especificado'),
('Z720','Uso do tabaco'),
('Z721','Uso de álcool'),
('Z722','Uso de droga'),
('Z723','Falta de exercício físico'),
('Z724','Regime e hábitos alimentares inadequados'),
('Z725','Comportamento sexual de alto risco'),
('Z726','Mania de jogo e apostas'),
('Z728','Outros problemas relacionados com o estilo de vida'),
('Z729','Problema não especificado relacionado com o estilo de vida'),
('Z730','Esgotamento'),
('Z731','Acentuação de traços de personalidade'),
('Z732','Falta de repouso e de lazer'),
('Z733','Stress não classificado em outra parte'),
('Z734','Habilidades sociais inadequadas não classificadas em outra parte'),
('Z735','Conflito sobre o papel social não classificado em outra parte'),
('Z736','Limites impostos às atividades por invalidez'),
('Z738','Outros problemas relacionados com a organização do seu modo de vida'),
('Z739','Problema relacionado com a organização de seu modo de vida não especificado'),
('Z740','Mobilidade reduzida'),
('Z741','Necessidade de assistência com cuidados pessoais'),
('Z742','Necessidade de assistência a domicílio sendo que nenhuma pessoa do lar é capaz de assegurar os cuidados'),
('Z743','Necessidade de supervisão contínua'),
('Z748','Outros problemas relacionados com a dependência de pessoa que oferece cuidados de saúde'),
('Z749','Problema não especificado relacionado com a dependência de pessoa que oferece cuidados de saúde'),
('Z750','Falta de disponibilidade de serviços médicos no domicílio'),
('Z751','Pessoa esperando ser admitida em estabelecimento médico adequado em outra parte'),
('Z752','Outro período de espera para investigação e tratamento'),
('Z753','Facilidades de saúde não disponíveis ou não acessíveis'),
('Z754','Outras organizações de cuidados não disponíveis ou não acessíveis'),
('Z755','Cuidados dispensados para ajudar às famílias durante as férias'),
('Z758','Outras dificuldades especificadas relacionadas com facilidades médicas e com outros cuidados de saúde'),
('Z759','Problema não especificado relacionado com facilidades médicas e com outros cuidados de saúde'),
('Z760','Emissão de prescrição de repetição'),
('Z761','Supervisão e cuidado de saúde de crianças assistidas'),
('Z762','Supervisão de cuidado de saúde de outras crianças ou recém-nascidos sadios'),
('Z763','Pessoa em boa saúde acompanhando pessoa doente'),
('Z764','Outros pensionistas em estabelecimentos de cuidados de saúde'),
('Z765','Pessoa fingindo ser doente [simulação consciente]'),
('Z768','Contatos com serviços de saúde por outras circunstâncias especificadas'),
('Z769','Pessoa em contato com serviços de saúde em circunstâncias não especificadas'),
('Z800','História familiar de neoplasia maligna de órgãos digestivos'),
('Z801','História familiar de neoplasia maligna de traquéia brônquio e pulmão'),
('Z802','História familiar de neoplasia maligna de outros órgãos respiratórios e intratorácicos'),
('Z803','História familiar de neoplasia de mama'),
('Z804','História familiar de neoplasia maligna de órgãos genitais'),
('Z805','História familiar de neoplasia maligna do trato urinário'),
('Z806','História familiar de leucemia'),
('Z807','História familiar de outras neoplasias malignas dos tecidos linfático hematopoético e correlacionados'),
('Z808','História familiar de neoplasia maligna de outros órgãos ou aparelhos'),
('Z809','História familiar de neoplasia maligna não especificada'),
('Z810','História familiar de retardo mental'),
('Z811','História familiar de abuso de álcool'),
('Z812','História familiar de abuso de fumo'),
('Z813','História familiar de abuso de outra substância psicoativa'),
('Z814','História familiar de abuso de outra substância'),
('Z818','História familiar de outros transtornos mentais e comportamentais'),
('Z820','História familiar de epilepsia e de outras doenças do sistema nervoso'),
('Z821','História familiar de cegueira e perda de visão'),
('Z822','História familiar de surdez e perda de audição'),
('Z823','História familiar de acidente vascular cerebral'),
('Z824','História familiar de doença isquêmica do coração e outras doenças do aparelho circulatório'),
('Z825','História familiar de asma e outras doenças respiratórias inferiores crônicas'),
('Z826','História familiar de artrite e outras doenças do sistema osteomuscular e tecido conjuntivo'),
('Z827','História familiar de malformações e deformações congênitas e anomalias cromossômicas'),
('Z828','História familiar de outras incapacidades e doenças crônicas que conduzem a incapacitação não classificadas em outra parte'),
('Z830','História familiar de doença pelo vírus da imunodeficiência humana [HIV]'),
('Z831','História familiar de outras doenças infecciosas e parasitárias'),
('Z832','História familiar de doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários'),
('Z833','História familiar de diabetes mellitus'),
('Z834','História familiar de outras doenças endócrinas nutricionais e metabólicas'),
('Z835','História familiar de outros transtornos dos olhos e dos ouvidos'),
('Z836','História familiar de doenças do aparelho respiratório'),
('Z837','História familiar das doenças do aparelho digestivo'),
('Z840','História familiar de doenças da pele e do tecido subcutâneo'),
('Z841','História familiar de transtornos do rim e ureter'),
('Z842','História familiar de outras doenças do aparelho geniturinário'),
('Z843','História familiar de consangüinidade'),
('Z848','História familiar de outras afecções especificadas'),
('Z850','História pessoal de neoplasia maligna de órgãos digestivos'),
('Z851','História pessoal de neoplasia maligna de traquéia brônquio e pulmão'),
('Z852','História pessoal de neoplasia maligna de outros órgãos respiratórios e intratorácicos'),
('Z853','História pessoal de neoplasia maligna de mama'),
('Z854','História pessoal de neoplasia maligna de órgãos genitais'),
('Z855','História pessoal de neoplasia maligna de trato urinário'),
('Z856','História pessoal de leucemia'),
('Z857','História pessoal de outras neoplasias malignas do tecido linfático hematopoético e tecidos correlatos'),
('Z858','História pessoal de neoplasias malignas de outros órgãos ou aparelhos'),
('Z859','História pessoal de neoplasia maligna não especificada'),
('Z860','História pessoal de outras neoplasias'),
('Z861','História pessoal de doenças infecciosas e parasitárias'),
('Z862','História pessoal de doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários'),
('Z863','História pessoal de doenças endócrinas nutricionais e metabólicas'),
('Z864','História pessoal de abuso de substâncias psicoativas'),
('Z865','História pessoal de outros transtornos mentais e comportamentais'),
('Z866','História pessoal de doenças do sistema nervoso e dos órgãos dos sentidos'),
('Z867','História pessoal de doenças do aparelho circulatório'),
('Z870','História pessoal de doenças do aparelho respiratório'),
('Z871','História pessoal de doenças do aparelho digestivo'),
('Z872','História pessoal de doenças da pele e tecido subcutâneo'),
('Z873','História pessoal de doenças do sistema osteomuscular e tecido conjuntivo'),
('Z874','História pessoal de doenças do aparelho geniturinário'),
('Z875','História pessoal de complicações da gravidez (parto e puerpério)'),
('Z876','História pessoal de algumas afecções originadas no período perinatal'),
('Z877','História pessoal de malformações e deformidades congênitas e anomalias cromossômicas'),
('Z878','História pessoal de outras afecções especificadas'),
('Z880','História pessoal de alergia à penicilina'),
('Z881','História pessoal de alergia a outro agente antibiótico'),
('Z882','História pessoal de alergia às sulfonamidas'),
('Z883','História pessoal de alergia a outros agentes antiinfecciosos'),
('Z884','História pessoal de alergia a agente anestésico'),
('Z885','História pessoal de alergia a agente narcótico'),
('Z886','História pessoal de alergia a agente analgésico'),
('Z887','História pessoal de alergia a soro e à vacina'),
('Z888','História pessoal de alergia a outros drogas medicamentos e substâncias biológicas'),
('Z889','História pessoal de alergia a drogas medicamentos e substâncias biológicas não especificadas'),
('Z890','Ausência adquirida de dedo(s) da mão [inclusive polegar] unilateral'),
('Z891','Ausência adquirida de mão e punho'),
('Z892','Ausência adquirida de braço acima do punho'),
('Z893','Ausência adquirida de ambos membros superiores [qualquer nível]'),
('Z894','Ausência adquirida de pé e tornozelo'),
('Z895','Ausência adquirida da perna ao nível ou abaixo do joelho'),
('Z896','Ausência adquirida da perna acima do joelho'),
('Z897','Ausência adquirida de ambos membros inferiores [qualquer nível exceto somente artelhos]'),
('Z898','Ausência adquirida dos membros superiores e inferiores [qualquer nível]'),
('Z899','Ausência adquirida de membro não especificado'),
('Z900','Ausência adquirida de parte da cabeça e do pescoço'),
('Z901','Ausência adquirida da(s) mama(s)'),
('Z902','Ausência adquirida [de parte] do pulmão'),
('Z903','Ausência adquirida de parte do estômago'),
('Z904','Ausência adquirida de outras partes do trato digestivo'),
('Z905','Ausência adquirida do rim'),
('Z906','Ausência adquirida de outras partes do trato urinário'),
('Z907','Ausência adquirida de órgão(s) genital(is)'),
('Z908','Ausência adquirida de outros órgãos'),
('Z910','História pessoal de alergia exceto a drogas e a substâncias biológicas'),
('Z911','História pessoal de não aderência a tratamento ou regime médico'),
('Z912','História pessoal de má higiene pessoal'),
('Z913','História pessoal de ciclo vigília-sono anormal'),
('Z914','História pessoal de trauma psicológico não classificado em outra parte'),
('Z915','História pessoal de auto agressão'),
('Z916','História pessoal de outros traumas físicos'),
('Z918','História pessoal de outros fatores de risco especificados não classificados em outra parte'),
('Z920','História pessoal de anticoncepção'),
('Z921','História pessoal de uso de longo prazo (atual) de anticoagulantes'),
('Z922','História pessoal de uso de longo prazo (atual) de outros medicamentos'),
('Z923','História pessoal de irradiação'),
('Z924','História pessoal de cirurgia de grande porte não classificada em outra parte'),
('Z925','História pessoal de medidas de reabilitação'),
('Z926','História pessoal de quimioterapia para doença neoplásica'),
('Z928','História pessoal de outros tratamentos médicos'),
('Z929','História pessoal de tratamento médico não especificado'),
('Z930','Traqueostomia'),
('Z931','Gastrostomia'),
('Z932','Ileostomia'),
('Z933','Colostomia'),
('Z934','Outros orifícios artificiais do trato gastrointestinal'),
('Z935','Cistostomia'),
('Z936','Outros orifícios artificiais do aparelho urinário'),
('Z938','Outros orifícios artificiais'),
('Z939','Orifício artificial não especificado'),
('Z940','Rim transplantado'),
('Z941','Coração transplantado'),
('Z942','Pulmão transplantado'),
('Z943','Coração e pulmões transplantados'),
('Z944','Fígado transplantado'),
('Z945','Pele transplantada'),
('Z946','Osso transplantado'),
('Z947','Córnea transplantada'),
('Z948','Outros órgãos e tecidos transplantados'),
('Z949','Órgão e tecido não especificado transplantado'),
('Z950','Presença de marca-passo cardíaco'),
('Z951','Presença de enxerto de ponte [bypass] aortocoronária'),
('Z952','Presença de prótese de válvula cardíaca'),
('Z953','Presença de valva cardíaca xenógena'),
('Z954','Presença de outras substituições valvares cardíacas'),
('Z955','Presença de implante e enxerto de angioplastia coronária'),
('Z958','Presença de outros implantes e enxertos cardíacos e vasculares'),
('Z959','Presença de implante e enxerto cardíaco e vascular não especificado'),
('Z960','Presença de implantes urogenitais'),
('Z961','Presença de lente intra-ocular'),
('Z962','Presença de implante otológicos e audiológicos'),
('Z963','Presença de laringe artificial'),
('Z964','Presença de implantes endócrinos'),
('Z965','Presença de raiz dentária e implantes mandibulares'),
('Z966','Presença de implantes articulares ortopédicos'),
('Z967','Presença de outros implantes de osso e tendão'),
('Z968','Presença de outros implantes funcionais especificados'),
('Z969','Presença de implante funcional não especificado'),
('Z970','Presença de olho artificial'),
('Z971','Presença de membro artificial (completo) (parcial)'),
('Z972','Presença de dispositivo protético dentário (completo) (parcial)'),
('Z973','Presença de óculos e de lentes de contato'),
('Z974','Presença de aparelho externo de surdez'),
('Z975','Presença de dispositivo anticoncepcional intra-uterino [DIU]'),
('Z978','Presença de outros dispositivos especificados'),
('Z980','Derivação intestinal ou anastomose intestinal'),
('Z981','Artrodese'),
('Z982','Presença de dispositivo de drenagem do líquor'),
('Z988','Outros estados pós-cirúrgicos especificados'),
('Z990','Dependência de aspirador'),
('Z991','Dependência de respirador'),
('Z992','Dependência de diálise renal'),
('Z993','Dependência de cadeira de rodas'),
('Z998','Dependência de outras máquinas e aparelhos capacitantes'),
('Z999','Dependência de máquina e aparelho capacitante não especificado'),
('U049','Síndrome respiratória aguda grave [Severe acute respiratory syndrome) [SARS] não especificada'),
('U800','Agente resistente à penicilina'),
('U801','Agente resistente à meticilina'),
('U808','Agente resistente a outro antibiótico relacionado à penicilina'),
('U810','Agente resistente à vancomicina'),
('U818','Agente resistente a outros antibióticos relacionado à vancomicina'),
('U88','Agente resistente a múltiplos antibióticos'),
('U898','Agente resistente a outro antibiótico especificado único'),
('U899','Agente resistente a antibiótico não especificado'),
('U99','CID 10ª Revisão não disponível')
;
""")

conn.commit()

print("Dados inseridos com sucesso!")

conn.close()



